### ISSUE TITLE
Redefine the mesh path for all robots to match URDF convention

### ISSUE THREAD

**Issue by cmastalli** [Gepetto/example-robot-data#19]
This task was partially done for the UR robot. We need to
 1. Modify all URDF files to match convention
 2. Add README documentation (optional)

**Comment by nim65s** [comment]
Why would we need any documentation ? The whole point is that everything should work out of the box in all cases, right ?

**Comment by cmastalli** [comment]
> Why would we need any documentation ? The whole point is that everything should work out of the box in all cases, right ?

Yes, I agree. But I am not sure if this possible. I didn't think about it.

**Comment by jcarpent** [comment]
Done.
