### ISSUE TITLE
Same configuration for 2 different posture names in solo_description/srdf

### ISSUE THREAD

**Issue by sduminy** [Gepetto/example-robot-data#2]
In the srdf file of the solo_desciption (https://github.com/Gepetto/example-robot-data/blob/master/solo_description/srdf/solo.srdf), both renamed postures "standing" and "straight_standing" correspond to the same configurations. Maybe one should be deleted ?

**Comment by nim65s** [comment]
cc @cmastalli

**Comment by cmastalli** [comment]
It is not the same. Note that the value of the hip abduction/adduction joint are different.

**Comment by cmastalli** [comment]
Feel free to reopen it.

And we could create other default postures if it is needed

**Comment by sduminy** [comment]
Okay, my bad, I didn't see. Thanks !
