### ISSUE TITLE
Anymal display is missing parts on MeshCat

### ISSUE THREAD

**Issue by wly2014** [Gepetto/example-robot-data#212]
May be like this [issue](https://github.com/Gepetto/example-robot-data/issues/177#issue-1789076946), the Anymal display also miss some parts on MeshCat.
```python
import example_robot_data
import time

# Loading the anymal model
anymal = example_robot_data.load("anymal",display=False)

# display in MeshCat
from pinocchio.visualize import MeshcatVisualizer
robot = anymal
q_max = robot.model.upperPositionLimit.T
q_min = robot.model.lowerPositionLimit.T
q0 = (q_min+q_max)/2

viz = MeshcatVisualizer(robot.model, robot.collision_model, robot.visual_model)
# Start a new MeshCat server and client.
viz.initViewer(open=True)
# Load the robot in the viewer.
viz.loadViewerModel()
viz.display(q0)

time.sleep(10.0)

```
displays:
![anymal](https://github.com/Gepetto/example-robot-data/assets/6903519/cfb8854b-237b-4b15-8760-581c1eaba1e8)

**Comment by cmastalli** [comment]
This is related to issues in Meshcat when supporting Collada files. Some related efforts can be seen in https://github.com/meshcat-dev/meshcat/pull/139 and https://github.com/meshcat-dev/meshcat/pull/170.

I will close this issue as we're not planning to handle this now.
