### ISSUE TITLE
Distinguish build and runtime dependencies

### ISSUE THREAD

**Issue by wxmerkt** [Gepetto/example-robot-data#22]
At present, Pinocchio is required as a build dependency in the CMakeLists. However, I think it should be a runtime dependency only as the Python files are _installed_ and there is no Pinocchio required to compile them.

Changing this avoids having a hard build-time dependency on Pinocchio, and also resolves the circular dependency by having this repository as a submodule in Pinocchio.

I think a viable proposition would be to remove the explicit dependency in the CMakeLists?

**Comment by cmastalli** [comment]
My only comment is we shouldn't make it a submodule of Pinocchio or any package. It's unnecessary complexity IMHO.
