### ISSUE TITLE
document robots origin & individual licences

### ISSUE THREAD

**Issue by nim65s** [Gepetto/example-robot-data#34]
Isn't it hazardous to provide files copied from other repository under a given license (except if the original license authorizes it) ?

_Originally posted by @jmirabel in https://github.com/Gepetto/example-robot-data/pull/33#issuecomment-646652583_

**Comment by nim65s** [comment]
And, obviously, double check that we can actually redistribute, and under which terms.

Many robots have been added by different people at different time, and we should have checked that each and every time, but we probably didn't.

**Comment by jcarpent** [comment]
I will push the original license for Panda then, you're right.
