### ISSUE TITLE
Add bolt robot

### ISSUE THREAD

**Issue by nim65s** [Gepetto/example-robot-data#71]
eg. from https://github.com/open-dynamic-robot-initiative/robot_properties_bolt/tree/master/src/robot_properties_bolt/robot_properties_bolt

thanks @gfadini for raising the issue :)

**Comment by cmastalli** [comment]
Awesome, thanks for taking care @nim65s!

**Comment by jviereck** [comment]
I can do this after finishing finger_edu in #91  if you want. Let me know.

**Comment by nim65s** [comment]
Sure, it would be wonderful if you could do that ! :D

**Comment by nim65s** [comment]
fixed in #94. Thanks @jviereck !
