### ISSUE TITLE
Is tiago_dual_robot.urdf provided?

### ISSUE THREAD

**Issue by hjw-1014** [Gepetto/example-robot-data#82]
Hi, I'm very new to urdf. I need a **TIAGo++** file, eg. tiago_dual_robot. 

Tiago robot (**tiago.urdf**) is provided here, but it has only one hand, so I wanna ask, Is there also **tiago_dual_robot.urdf** provided or should I edit urdf of **tiado.urdf** here to add an arm?

I found[ here ](https://github.com/pal-robotics/tiago_robot), tiago_dual_description is provided, but inside is xacro file. 

Thanks in advance.

**Comment by nim65s** [comment]
Hi,

I think I can add this robot here. I'll give it a try tomorrow.

**Comment by hjw-1014** [comment]
> Hi,
> 
> I think I can add this robot here. I'll give it a try tomorrow.

Thank you so much, that would help me a lot.
