### ISSUE TITLE
Using meshes provided by example-robot-data

### ISSUE THREAD

**Issue by florent-lamiraux** [Gepetto/example-robot-data#9]
Following recent discussions, I propose to move forward in  the direction of using meshes provided by example-robot-data instead of native description packages.

I will propose a pull request handling robots for which I will have tested that this does not break anything when loading models.

I also propose to revert commit ed85b87 since @cmastalli uses the lighting provided by the models.

**Comment by cmastalli** [comment]
Sounds good for me.

Thanks for taking care @florent-lamiraux

**Comment by jcarpent** [comment]
Done.
