### ISSUE TITLE
Add FingerEdu robot

### ISSUE THREAD

**Issue by jviereck** [Gepetto/example-robot-data#90]
If possible, I would like to add the FingerEdu to the example-robot-data package. We use this 3-dim fixed-base robot as educational platform for teaching. If the students can pip/conda-install the robot, it would make our life much easier.

If you are okay to add it I can try to make a PR.

**Comment by jviereck** [comment]
Here is the link to the robot: https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/finger_edu_v1/README.md#fingeredu-v1

![image](https://user-images.githubusercontent.com/191719/121790381-dd25fd80-cbac-11eb-8b0b-ec449631eba9.png)

**Comment by jcarpent** [comment]
Yes, sure! This is more than welcome. You can proceed with a new PR. Thanks a lot @jviereck for this suggestion.
