### ISSUE TITLE
Relicense or Remove Tiago

### ISSUE THREAD

**Issue by nim65s** [Gepetto/example-robot-data#99]
As found by #98, Tiago is licensed by a [Creative Commons BY-NC-ND 3.0](https://github.com/pal-robotics/tiago_robot/blob/kinetic-devel/tiago_description/package.xml#L12), which clearly forbids us to distribute this derivated work.

We should either :
- kindly ask PAL-Robotics  to either reconsider the license of their work, or to explicitely give us an exception
- remove Tiago from example-robot-data

**Comment by cmastalli** [comment]
I believe we should ask PAL first and explain them our mistake. Otherwise, we have to remove it.

Removing the Tiago robot might repercute many folks. So, if needed, we should print a deprecated message explaining the major reasons for the remotion.

**Comment by jcarpent** [comment]
Tiago and Talos do not have the same license?

**Comment by nim65s** [comment]
no

**Comment by nim65s** [comment]
I got an oral confirmation from PAL CEO & CTO: we can keep working like that. They will fix the license on their side when they will have time.
